path:
  root: "data/loveda"
  output_dir: "temp"
  train_dir: "Train"
  val_dir: "Val"
  source: "Urban"
  target: "Urban"
  images: "images_png"
  masks: "masks_png"
  checkpoints: "models/checkpoints"
  checkpoint_path: null
  weights: "models/pretrained_weights"
  pretrained_path: null

data:
  imagenet_mean: [0.485, 0.456, 0.406]
  imagenet_std: [0.229, 0.224, 0.225]
  batch_size: 6
  dimensions:
    height: 1024
    width: 1024
  downscale: null
  resize:
    height: 512
    width: 512
  augment: false
  aug_prob: 1
  aug_prob_one_of: 0.75
  aug_names:
    RC:
      height: 512
      width: 512
    HF: {}
    VF: {}
    RR: {}

model:
  model: "pidnet_s"
  checkpoint: null
  ignore_index: -1
  num_classes: 7

training:
  train: true
  evaluate: true
  measure: false
  resume: false
  adaptation: null
  epochs: 60
  loss: "ohem"
  weighted_loss: false
  ohem_keep: 32768
  ohem_threshold: 0.9
  focal_gamma: 2.0
  optimizer: "SGD"
  scheduler: "poly"
  power: 0.9
  eta_min: 1.e-6
  learning_rate: 
    pidnet_s: 
      - 1.e-4
      - 1.e-3
    bisenet_v1_rt:
      - 1.e-4
      - 1.e-3
    bisenet_v1:
      - 1.e-4
      - 1.e-3
    stdc1:
      - 1.e-4
      - 1.e-3
    deeplab_v2:
      - 1.e-4
      - 1.e-3
  weight_decay: 5.e-4
  step_size: 10
  gamma: 0.1
  momentum: 0.9

adda:
  lambda_adv: 0.01
  adda_num_classes: 7
  adda_optimizer: "Adam"
  adda_scheduler: "poly"
  adda_power: 0.9
  adda_eta_min: 1.e-6
  adda_learning_rate: 1.e-4
  adda_weight_decay: 5.e-3
  adda_step_size: 10
  adda_gamma: 0.1
  adda_momentum: 0.9